/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.baezdaniel.telexample;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {
    @Test 
    void contextLoads() {
        // Test that the Spring context loads successfully
    }
}
