/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.baezdaniel.telexample;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Simple application startup test
 */
@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = "endpoint.auth.enabled=false")
class AppTest {

    @Test
    void contextLoads() {
        // Test that the Spring application context loads successfully
        assertThat(true).isTrue();
    }
}
